### ISSUE TITLE
🚀 [feature] 경기 결과 및 검색 관련 세팅

### ISSUE THREAD

**Issue by FutureandKim** [wekick/wekick-service#14]
# 🤖 기능 개요
경기 결과 및 검색 관련 세팅
## ✅ Todo
- [ ] 경기 평가 관련 세팅
- [ ] 경기 결과 관련 세팅
- [ ] 개인, 크루 검색 관련 세팅
