### ISSUE TITLE
🚀 [feature] 개인, 크루 랭킹 구현

### ISSUE THREAD

**Issue by FutureandKim** [wekick/wekick-service#25]
# 🤖 기능 개요
개인, 크루 랭킹 api
## ✅ Todo
- [ ] 승률 계산 로직 구현 및 DB 저장
- [ ] 개인 랭킹 - 평점, 매너, 실력, 분위기메이커 api
- [ ] 크루 랭킹 - 실력, 승률 api
