### ISSUE TITLE
🚀 [feature] 매칭 로직 구현 및 크루 가입하기 API 구현

### ISSUE THREAD

**Issue by koojun99** [wekick/wekick-service#28]
# 🤖 기능 개요

매칭 로직 구현 및 크루 가입하기 API 구현
## ✅ Todo
- [ ] 매치 상세보기 - 팀 배정 
- [ ] 매치 참여 취소하기
- [ ] 크루 초대 수락하여 가입하기
